server:
  port: 8080

spring:
  application:
    name: cloud-gateway
   
logging:
  level:
    '[org.springframework.cloud.gateway,reactor.netty.http.client]': trace

        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true     
    service-url:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    