server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: review-module
        uri: lb://REVIEW-SERVICE
        predicates:
        - Path=/api/v1/reviews/** 
  application:
    name: cloud-gateway
   
logging:
  level:
    '[org.springframework.cloud.gateway]': trace

        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true     
    service-url:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    