server:
    port: 7575
spring:
  application:
    name: recommend-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update            

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
 