spring:
  application:
    name: product-service
  datasource:    username: root
    url: jdbc:mysql://localhost:3306/test
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true
    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      ddl-auto: update            
