spring:
  config:
    activate:
      on-profile:
      - peer-1
    
server:
  port: 8770

logging:
  level:
    '[org.springframework.boot]': trace  
---

spring:
  config:
    activate:
      on-profile:
      - peer-2

logging:
  level:
    '[org.springframework.boot]': info  

server:
  port: 8775
  